#!/bin/bash
# Post-Commit Hook: Execute git feature-commit after each commit

COMMIT_ID=$(git rev-parse HEAD)
git feature-commit $COMMIT_ID

if [ $? -ne 0 ]; then
    echo "Error: git feature-commit failed."
    exit 1
fi

exit 0
