#!/bin/bash
# Pre-Commit Hook: Assert that feature changes were staged and the script does not find reasons to not continue

git feature-pre-commit

if [ $? -ne 0 ]; then
  echo "Error: Pre-commit checks failed."
  exit 1 # exiting non-zero aborts the commit
fi
