#!/bin/bash
# Prepare Commit Message Hook: Modify the commit message to include feature information

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

FEATURE_MSG=$(git feature-commit-msg)

if [ $? -ne 0 ]; then
    echo "Error: Failed to generate feature commit message."
    exit 0 # Sometimes an overwrite is necessary. still not sure how to handle. but the message is optional
fi

if [ "$FEATURE_MSG" ]; then
    echo -e "\n\n$FEATURE_MSG" >> "$COMMIT_MSG_FILE"
else
    echo "Feature information not found: $FEATURE_MSG"
fi
